[package]
name = "merch_store"
version = "0.1.0"
edition = "2024"
default-run = "merch_store"

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["tracing"] }
daraja-sdk = "0.3.0"
jiff = "0.2.35"
serde = { version = "1.0.229", features = ["derive"] }
toasty = { version = "0.9.0", features = ["mysql", "jiff"] }
toasty-cli = "0.9.0"
tokio = { version = "1.53.1", features = ["rt", "macros", "rt-multi-thread"] }
toml = "1.1.4"
tower = { version = "0.5.3", features = ["tracing"] }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
